CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(200) NOT NULL,
  email VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS companies (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(100) NOT NULL,
  address VARCHAR(200) NOT NULL,
  "accessToken" VARCHAR(100) NOT NULL UNIQUE,
  "isTaxpayer" BOOLEAN NOT NULL DEFAULT FALSE,
  phone VARCHAR(15),
  "taxNumber" VARCHAR(10),
  iban VARCHAR(34),
  email VARCHAR(100),
  "defaultIssuer" BOOLEAN NOT NULL DEFAULT false
);

CREATE TYPE EQUIPMENT_TYPE AS ENUM ('TRACTOR', 'TRUCK', 'LOADER', 'FORKLIFT', 'PLOW', 'MULCHER', 'SPRAYER', 'BALER', 'TRAILER', 'COMBINE_HARVESTER', 'SEEDER', 'MOWER', 'CULTIVATOR', 'OTHER');
CREATE TABLE IF NOT EXISTS equipment (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(100) NOT NULL,
  "nextService" DATE,
  "nextServiceHours" INT,
  hours INT NOT NULL DEFAULT 0,
  "equipmentType" EQUIPMENT_TYPE NOT NULL DEFAULT 'OTHER'
);

CREATE TABLE IF NOT EXISTS service (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(100) NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  hours INT,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  cost NUMERIC NOT NULL DEFAULT 0.00,
  equipment_id INT NOT NULL REFERENCES equipment(id)
);

CREATE TABLE IF NOT EXISTS plots (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(100) NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  boundary GEOMETRY(POLYGON, 3794) NOT NULL,
  bbox BOX2D NOT NULL,
  "plotSize" INT NOT NULL,
  "plotNumber" VARCHAR(40) NOT NULL,
  "cadastralMunicipality" INTEGER NOT NULL,
  archived BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS invoice (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(100) NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  started DATE NOT NULL DEFAULT CURRENT_DATE,
  ended DATE,
  "isPaid" BOOLEAN NOT NULL DEFAULT false,
  "dueDate" DATE,
  customer_id INT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  issuer_id INT NOT NULL REFERENCES companies(id) ON DELETE CASCADE
);

CREATE TYPE QUANTITY_TYPE AS ENUM ('price_per_hour', 'price_per_piece', 'price_per_area');
CREATE TABLE IF NOT EXISTS jobType (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(100) NOT NULL,
  "quantityType" QUANTITY_TYPE NOT NULL,
  price NUMERIC NOT NULL
);

CREATE TABLE IF NOT EXISTS job (
  id SERIAL PRIMARY KEY NOT NULL,
  quantity INT NOT NULL,
  price NUMERIC NOT NULL,
  "totalPrice" NUMERIC NOT NULL,
  "timeTaken" INT NOT NULL,
  invoice_id INT NOT NULL REFERENCES invoice(id) ON DELETE CASCADE,
  jobType_id INT NOT NULL REFERENCES jobType(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS job_has_plot (
  id SERIAL PRIMARY KEY NOT NULL,
  job_id INT NOT NULL REFERENCES job(id) ON DELETE CASCADE,
  plot_id INT NOT NULL REFERENCES plot(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS job_has_equipment (
  id SERIAL PRIMARY KEY NOT NULL,
  job_id INT NOT NULL REFERENCES job(id) ON DELETE CASCADE,
  equipment_id INT NOT NULL REFERENCES equipment(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cost (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(100) NOT NULL,
  amount NUMERIC NOT NULL,
  job_id INT NOT NULL REFERENCES job(id) ON DELETE CASCADE
);